name: docker-push-master

# Only runs on pushes to master
on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'


jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push master image
        uses: docker/build-push-action@v1.0.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/10x_neural_tube
          tags: v1.0